import { TriviaQuestion } from './types';

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  {
    id: 'q1',
    question: 'When did Stratos first launch in Norway?',
    options: ['1936', '1954', '1971', '1998'],
    correctOptionIndex: 1,
    note: 'Classic Stratos fun fact.',
  },
  {
    id: 'q2',
    question: 'What gives Stratos-style bubbly chocolate its airy texture?',
    options: ['Tiny air bubbles', 'Extra sugar crystals', 'Whipped milk foam', 'Caramel threads'],
    correctOptionIndex: 0,
  },
  {
    id: 'q3',
    question: 'Stratos is usually known as what type of chocolate?',
    options: ['Milk chocolate', 'Dark mint chocolate', 'White chocolate', 'Ruby chocolate'],
    correctOptionIndex: 0,
  },
  {
    id: 'q4',
    question: 'Which bite sensation is most associated with Stratos?',
    options: ['Crispy wafers', 'Bubbly melt', 'Chewy caramel center', 'Icy crunch'],
    correctOptionIndex: 1,
  },
  {
    id: 'q5',
    question: 'A playful nickname for Stratos bubbles could be:',
    options: ['Bubble bites', 'Salt sparks', 'Mint dots', 'Cocoa rocks'],
    correctOptionIndex: 0,
  },
  {
    id: 'q6',
    question: 'Stratos branding is often linked to which feeling?',
    options: ['Heavy and intense', 'Light and fun', 'Savory and smoky', 'Sour and sharp'],
    correctOptionIndex: 1,
  },
  {
    id: 'q7',
    question: 'Which of these sounds most like a Stratos snack moment?',
    options: ['On a ski trip break', 'In a soup bowl', 'With hot sauce', 'At a hardware store aisle'],
    correctOptionIndex: 0,
    note: 'Fun-facts style question.',
  },
  {
    id: 'q8',
    question: 'What is the best way to enjoy bubbly chocolate texture?',
    options: ['Take a small bite and let it melt', 'Freeze solid and chew fast', 'Boil it first', 'Mix with vinegar'],
    correctOptionIndex: 0,
  },
  {
    id: 'q9',
    question: 'Which option fits a classic Stratos product style best?',
    options: ['Smooth bar with bubbles', 'Hard candy cube', 'Chocolate syrup bottle', 'Chocolate tea bag'],
    correctOptionIndex: 0,
  },
  {
    id: 'q10',
    question: 'Stratos is most closely associated with which country?',
    options: ['Norway', 'Mexico', 'India', 'New Zealand'],
    correctOptionIndex: 0,
  },
  {
    id: 'q11',
    question: 'If a Stratos bar is very warm, the bubbles may feel:',
    options: ['Softer and less defined', 'Sharper and crunchier', 'Saltier', 'More sour'],
    correctOptionIndex: 0,
  },
  {
    id: 'q12',
    question: 'Which color palette best matches Stratos app/game styling?',
    options: ['Deep blue with light text', 'Orange and black stripes', 'Pink neon only', 'Beige and brown only'],
    correctOptionIndex: 0,
  },
  {
    id: 'q13',
    question: 'A playful Stratos trivia round should feel:',
    options: ['Friendly and quick', 'Long and stressful', 'Silent and formal', 'Complicated and technical'],
    correctOptionIndex: 0,
  },
  {
    id: 'q14',
    question: 'What is a good pairing with a Stratos milk chocolate snack?',
    options: ['A cup of coffee or milk', 'Pickled onions', 'Hot chili oil', 'Soy sauce'],
    correctOptionIndex: 0,
  },
  {
    id: 'q15',
    question: 'Why do people like bubbly bars such as Stratos?',
    options: ['Unique airy mouthfeel', 'They are always salty', 'They never melt', 'They contain no cocoa'],
    correctOptionIndex: 0,
  },
  {
    id: 'q16',
    question: 'Stratos fun-fact tone is usually:',
    options: ['Playful and light', 'Strictly academic', 'Serious legal style', 'Silent and minimal'],
    correctOptionIndex: 0,
  },
  {
    id: 'q17',
    question: 'Which feature best supports a Stratos trivia replay experience?',
    options: ['Randomized questions', 'One fixed question forever', 'No scoring', 'No answer options'],
    correctOptionIndex: 0,
  },
  {
    id: 'q18',
    question: 'In a Stratos quiz, points are mainly awarded for:',
    options: ['Correct answers', 'Longest username', 'Phone battery level', 'Screen brightness'],
    correctOptionIndex: 0,
  },
  {
    id: 'q19',
    question: 'A leaderboard in Stratos trivia should show:',
    options: ['Score and date', 'Passport number', 'GPS route', 'Favorite movie'],
    correctOptionIndex: 0,
  },
  {
    id: 'q20',
    question: 'Which of these is most “on-brand” for Stratos trivia feedback?',
    options: ['Correct ✅ / Wrong ❌', 'Binary memory dump', 'No feedback at all', 'Long legal paragraph'],
    correctOptionIndex: 0,
  },
  {
    id: 'q21',
    question: 'If Stratos bubbles are the star, what should the texture be?',
    options: ['Light and aerated', 'Dense and gummy', 'Dry and chalky', 'Watery'],
    correctOptionIndex: 0,
  },
  {
    id: 'q22',
    question: 'Which type of mini-game fits Stratos app style best?',
    options: ['Short rounds and fun facts', 'Three-hour simulations', 'Spreadsheet training', 'Silent typing drills'],
    correctOptionIndex: 0,
  },
  {
    id: 'q23',
    question: 'A good Stratos trivia question should be:',
    options: ['Short and easy to tap through', 'Five paragraphs long', 'Without answer options', 'Only for experts'],
    correctOptionIndex: 0,
  },
  {
    id: 'q24',
    question: 'Which statement is safest as a Stratos-friendly fun fact?',
    options: ['Bubbly texture creates a lighter bite feeling', 'Chocolate never melts', 'All chocolate is sugar-free', 'Cocoa grows in snow'],
    correctOptionIndex: 0,
    note: 'Fun-facts style wording.',
  },
  {
    id: 'q25',
    question: 'Which ingredient mainly makes milk chocolate creamy?',
    options: ['Milk solids', 'Sea salt', 'Corn starch', 'Vinegar'],
    correctOptionIndex: 0,
  },
  {
    id: 'q26',
    question: 'Best temperature range for storing chocolate at home is usually:',
    options: ['10–15°C', '2–5°C', '24–30°C', '35–40°C'],
    correctOptionIndex: 0,
    note: 'Cool, dry, and stable works best.',
  },
  {
    id: 'q27',
    question: 'Chocolate “bloom” mostly appears when:',
    options: ['Temperature changes too much', 'Chocolate is too fresh', 'It is kept in darkness', 'It contains cocoa'],
    correctOptionIndex: 0,
  },
  {
    id: 'q28',
    question: 'Which cocoa percentage is usually sweetest?',
    options: ['30%', '55%', '70%', '85%'],
    correctOptionIndex: 0,
  },
  {
    id: 'q29',
    question: 'Cocoa beans grow on:',
    options: ['Cacao trees', 'Pine trees', 'Grape vines', 'Wheat stalks'],
    correctOptionIndex: 0,
  },
  {
    id: 'q30',
    question: 'What is a classic flavor pairing for milk chocolate?',
    options: ['Sea salt', 'Garlic powder', 'Curry paste', 'Ketchup'],
    correctOptionIndex: 0,
  },
  {
    id: 'q31',
    question: 'Which country is often ranked high in per-person chocolate consumption?',
    options: ['Switzerland', 'Egypt', 'Peru', 'Indonesia'],
    correctOptionIndex: 0,
    note: 'Fun-facts style question.',
  },
  {
    id: 'q32',
    question: 'Why keep chocolate away from direct sunlight?',
    options: ['It can melt and lose texture', 'It becomes more bubbly', 'It gets sweeter', 'It gains protein'],
    correctOptionIndex: 0,
  },
  {
    id: 'q33',
    question: 'Dark chocolate usually has:',
    options: ['Higher cocoa content', 'No cocoa at all', 'Only milk powder', 'Only caramel'],
    correctOptionIndex: 0,
  },
  {
    id: 'q34',
    question: 'Which texture word often describes good tempered chocolate?',
    options: ['Snappy', 'Rubbery', 'Sticky', 'Foamy'],
    correctOptionIndex: 0,
  },
  {
    id: 'q35',
    question: 'The main source ingredient for chocolate is:',
    options: ['Cocoa beans', 'Coffee beans', 'Vanilla pods', 'Oat flakes'],
    correctOptionIndex: 0,
  },
  {
    id: 'q36',
    question: 'If chocolate absorbs strong odors, it may taste:',
    options: ['Off-flavor or strange', 'Always minty', 'Extra bubbly', 'More neutral'],
    correctOptionIndex: 0,
  },
  {
    id: 'q37',
    question: 'What does cocoa butter mainly contribute to chocolate?',
    options: ['Smooth melt and texture', 'Spicy heat', 'Sourness', 'Blue color'],
    correctOptionIndex: 0,
  },
  {
    id: 'q38',
    question: 'Milk chocolate compared with dark chocolate is often:',
    options: ['Creamier and sweeter', 'More bitter and dry', 'Saltier', 'Spicier'],
    correctOptionIndex: 0,
  },
  {
    id: 'q39',
    question: 'A fun way to enjoy chocolate mindfully is to:',
    options: ['Let it melt slowly', 'Microwave until boiling', 'Mix with soda water', 'Store it in sunlight'],
    correctOptionIndex: 0,
  },
  {
    id: 'q40',
    question: 'For a balanced chocolate quiz, what helps replay value most?',
    options: ['A larger randomized question bank', 'Only one repeated question', 'No score tracking', 'No answer feedback'],
    correctOptionIndex: 0,
  },
];
